//USERS
export const GOOGLE_SIGIN = 'GOOGLE_SIGIN'
export const FB_SIGNIN = 'FB_SIGNIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const CHECK_LOGIN = 'CHECK_LOGIN'

export const UPDATE_ALL_USERS = 'UPDATE_ALL_USERS'

//LOCATION
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SEARCH_GOOGLE_PLACE = 'SEARCH_GOOGLE_PLACE'
export const SEARCH_GOOGLE_PLACE_MEETUP = 'SEARCH_GOOGLE_PLACE_MEETUP'
export const CHANGE_MAPTYPE = 'CHANGE_MAPTYPE'
export const TOGGLE_DIRECTION = 'TOGGLE_DIRECTION'
export const CLOSE_DIRECTION = 'CLOSE_DIRECTION'
export const SET_PLACE_FROM = 'SET_PLACE_FROM'
export const SET_PLACE_TO = 'SET_PLACE_TO'
export const SET_CURRENT_PLACE = 'SET_CURRENT_PLACE'

//NEW MEETUPS
export const UPDATE_MEETUP_FRIENDS = 'UPDATE_MEETUP_FRIENDS'
export const MEETUP_NAME = 'MEETUP_NAME'
export const MEETUP_DATE = 'MEETUP_DATE'
export const MEETUP_TIME = 'MEETUP_TIME'
export const MEETUP_CLEAR_FORM = 'MEETUP_CLEAR_FORM'
export const UPDATE_MEETUP_LIST = 'UPDATE_MEETUP_LIST'

//REQUESTS
export const UPDATE_MEETUP_REQUEST = 'UPDATE_MEETUP_REQUEST'
export const UPDATE_FRIEND_REQUEST = 'UPDATE_FRIEND_REQUEST'

//FRIENDS
export const UPDATE_FRIENDS_LABEL = 'UPDATE_FRIENDS_LABEL'



